sudo: required
services:
 - docker

before_install:
 - docker build -t evgenijavstein/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true evgenijavstein/react-test npm test

after_success:
 - docker build -t evgenijavstein/multi-client ./client
 - docker build -t evgenijavstein/multi-nginx ./nginx
 - docker build -t evgenijavstein/multi-server ./server
 - docker build -t evgenijavstein/multi-worker ./worker

# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to dockerhub
 - docker push evgenijavstein/multi-client
 - docker push evgenijavstein/multi-nginx
 - docker push evgenijavstein/multi-server
 - docker push evgenijavstein/multi-worker

# end of file